controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint"]
      right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint"]
      wheel_separation: 0.35
      wheel_radius: 0.04
      base_frame_id: base_footprint
      cmd_vel_timeout: 0.5
      use_stamped_vel: false
      enable_odom_tf: true
