controller_manager:
  ros__parameters:
    update_rate: 50

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint"]
    wheel_separation: 0.35
    wheel_radius: 0.04
    odom_frame_id: odom
    base_frame_id: base_footprint