Camera.type: "Stereo"

Camera.fx: 320.0
Camera.fy: 320.0
Camera.cx: 320.0
Camera.cy: 240.0
Camera.width: 640
Camera.height: 480
Camera.fps: 30
Camera.RGB: 1

Camera.bf: 40.0   # fx * baseline (baseline = distance between cameras)
Camera.ThDepth: 40.0

Stereo.b: 0.12    # Baseline in meters
Stereo.Tolerance: 0.05

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
